export const ADMIN_SIGNUP_SUCCESS = "ADMIN_SIGNUP_SUCCESS";
export const ADMIN_SIGNUP_ERROR = "ADMIN_SIGNUP_ERROR";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_ERROR = "ADMIN_LOGIN_ERROR";
//              Vendor
export const ADD_VENDOR_SUCCESS = "ADD_VENDOR_SUCCESS";
export const ADD_VENDOR_ERROR = "ADD_VENDOR_ERROR";
export const MANAGE_VENDOR = "MANAGE_VENDOR";
export const MANAGE_VENDOR_ERROR = "MANAGE_VENDOR_ERROR";
export const DELETE_VENDOR_SUCCESS = "DELETE_VENDOR_SUCCESS";
export const DELETE_VENDOR_ERROR = "DELETE_VENDOR_ERROR";
export const UPDATE_VENDER_SUCCESS = "UPDATE_VENDER_SUCCESS";
export const UPDATE_VENDER_ERROR = "UPDATE_VENDER_ERROR";
export const SEARCH_VENDER_BY_NAME = "SEARCH_VENDER_BY_NAME";
//              Stock
export const ADD_STOCK_SUCCESS = "ADD_STOCK_SUCCESS";
export const ADD_STOCK_ERROR = "ADD_STOCK_ERROR";
export const SHOW_STOCK_LIST_SUCCESS = "SHOW_STOCK_LIST_SUCCESS";
export const SHOW_STOCK_LIST_ERROR = "SHOW_STOCK_LIST_ERROR";
export const SHOW_EXPIRE_STOCK_SUCCESS = "SHOW_EXPIRE_STOCK_SUCCESS";
export const SHOW_EXPIRE_STOCK_ERROR = "SHOW_EXPIRE_STOCK_ERROR";
export const SHOW_EXPIRE_MEDICINE_SUCCESS = "SHOW_EXPIRE_MEDICINE_SUCCESS";
export const SHOW_EXPIRE_MEDICINE_ERROR = "SHOW_EXPIRE_MEDICINE_ERROR";
export const SEARCH_STOCK_BY_NAME = "SEARCH_STOCK_BY_NAME";
export const EXPIRED_MEDICINE_STOCK = "EXPIRED_MEDICINE_STOCK";
export const OUT_OF_STOCK = "OUT_OF_STOCK";
//               Add Medicine Type Action
export const ADD_MEDICINE_TYPE_SUCCESS = "ADD_MEDICINE_TYPE_SUCCESS";
export const ADD_MEDICINE_TYPE_ERROR = "ADD_MEDICINE_TYPE_ERROR";
export const SHOW_MEDICINE_TYPE_LIST_SUCCESS =
  "SHOW_MEDICINE_TYPE_LIST_SUCCESS";
export const SHOW_MEDICINE_TYPE_LIST_ERROR = "SHOW_MEDICINE_TYPE_LIST_ERROR";
export const DELETE_MEDICINE_TYPE_SUCCESS = "DELETE_MEDICINE_SUCCESS";
export const DELETE_MEDICINE_TYPE_ERROR = "DELETE_MEDICINE_ERROR";
export const UPDATE_MEDICINE_TYPE_SUCCESS = "UPDATE_MEDICINE_TYPE_SUCCESS";
export const UPDATE_MEDICINE_TYPE_ERROR = "UPDATE_MEDICINE_TYPE_ERROR";
export const SEARCH_MEDICINE_TYPE = "SEARCH_MEDICINE_TYPE";
//                 Employee
export const ADD_EMPLOYEE_SUCCESS = "ADD_EMPLOYEE_SUCCESS";
export const ADD_EMPLOYEE_ERROR = "ADD_EMPLOYEE_ERROR";
export const SHOW_EMPLOYEE_LIST_SUCCESS = "SHOW_EMPLOYEE_LIST_SUCCESS";
export const SHOW_EMPLOYEE_LIST_ERROR = "SHOW_EMPLOYEE_LIST_ERROR";
export const UPDATE_EMPLOYEE_SUCCESS = "UPDATE_EMPLOYEE_SUCCESS";
export const UPDATE_EMPLOYEE_ERROR = "UPDATE_EMPLOYEE_ERROR";
export const BLOCK_EMPLOYEE_SUCCESS = "BLOCK_EMPLOYEE_SUCCESS";
export const BLOCK_EMPLOYEE_ERROR = "BLOCK_EMPLOYEE_ERROR";
export const UNBLOCK_EMPLOYEE_ERROR = "UNBLOCK_EMPLOYEE_ERROR";
export const UNBLOCK_EMPLOYEE_SUCCESS = "UNBLOCK_EMPLOYEE_SUCCESS";
export const SEARCH_EMPLOYEE_BY_NAME = "SEARCH_EMPLOYEE_BY_NAME";
//                  Company
export const ADD_COMPANY_SUCCESS = "ADD_COMPANY_SUCCESS";
export const ADD_COMPANY_ERROR = "ADD_COMPANY_ERROR";
export const SHOW_COMPANY_SUCCESS = "SHOW_COMPANY_SUCCESS";
export const SHOW_COMPANY_ERROR = "SHOW_COMPANY_ERROR";
export const UPDATE_COMPANY_SUCCESS = "UPDATE_COMPANY_SUCCESS";
export const UPDATE_COMPANY_ERROR = "UPDATE_COMPANY_ERROR";
export const DELETE_COMPANY_SUCCESS = "DELETE_COMPANY_SUCCESS";
export const DELETE_COMPANY_ERROR = "DELETE_COMPANY_ERROR";
export const SEARCH_COMPANY_BY_NAME = "SEARCH_COMPANY_BY_NAME";
//                  Add Medicine
export const ADD_MEDICINE_SUCCESS = "ADD_MEDICINE_SUCCESS";
export const ADD_MEDICINE_ERROR = "ADD_MEDICINE_ERROR";
export const SHOW_MEDICINE_SUCCESS = "SHOW_MEDICINE_SUCCESS";
export const SHOW_MEDICINE_ERROR = "SHOW_MEDICINE_ERROR";
export const DELETE_MEDICINE_SUCCESS = "DELETE_MEDICINE_SUCCESS";
export const DELETE_MEDICINE_ERROR = "DELETE_MEDICINE_ERROR ";
export const SEND_MEDICINE_SUCCESS = "SEND_MEDICINE_SUCCESS";
export const SEND_MEDICINE_ERROR = "SEND_MEDICINE_ERROR";
export const UPDATE_MEDICINE_SUCCESS = "UPDATE_MEDICINE_SUCCESS";
export const UPDATE_MEDICINE_ERROR = "UPDATE_MEDICINE_ERROR";
export const SEARCH_MEDICINE_BY_NAME = "SEARCH_MEDICINE_BY_NAME";
//                  Add Unit
export const ADD_UNIT_SUCCESS = "ADD_UNIT_SUCCESS";
export const ADD_UNIT_ERROR = "ADD_UNIT_ERROR";
export const SHOW_UNIT_LIST_SUCCESS = "SHOW_UNIT_LIST_SUCCESS";
export const SHOW_UNIT_LIST_ERROR = "SHOW_UNIT_LIST_ERROR";
export const DELETE_UNIT_LIST_SUCCESS = "DELETE_UNIT_LIST_SUCCESS";
export const DELETE_UNIT_LIST_ERROR = "DELETE_UNIT_LIST_ERROR";
export const UPDATE_UNIT_LIST_SUCCESS = "UPDATE_UNIT_LIST_SUCCESS";
export const UPDATE_UNIT_LIST_ERROR = "UPDATE_UNIT_LIST_ERROR";
export const SEARCH_UNIT_LIST = "SEARCH_UNIT_LIST";
//                  Medicine Searching
export const SEARCH_MEDICINE_BY_SALT_SUCCESS =
  "SEARCH_MEDICINE_BY_SALT_SUCCESS";
export const SEARCH_MEDICINE_BY_SALT_ERRROR = "SEARCH_MEDICINE_BY_SALT_ERRROR";
export const SEARCH_MEDICINE_BY_NAME_SUCCESS =
  "SEARCH_MEDICINE_BY_NAME_SUCCESS";
export const SEARCH_MEDICINE_BY_NAME_ERROR = "SEARCH_MEDICINE_BY_NAME_ERROR";
export const SEARCH_DATA_FROM_INVOICE = "SEARCH_DATA_FROM_INVOICE";
export const SEARCH_DATA_NAME_INVOICE = "SEARCH_DATA_NAME_INVOICE";
export const SELECTED_QUNTITY_DATA = "SELECTED_QUNTITY_DATA";
export const TOTAL_PRICE_EACH_MEDICINE = "TOTAL_PRICE_EACH_MEDICINE";
export const DELETE_INVOICE_ROW_DATA = "DELETE_INVOICE_ROW_DATA";
//                GSt Action Types
export const GET_GST_DATA_SUCCESS = "GET_GST_DATA_SUCCESS";
export const GET_GST_DATA_ERROR = "GET_GST_DATA_ERROR";
export const UPADTE_GST_DATA_SUCCESS = "UPADTE_GST_DATA_SUCCESS";
export const UPADTE_GST_DATA_ERROR = "UPADTE_GST_DATA_ERROR";
export const UPDATE_DICOUNT_DATA_SUCCESS = "UPDATE_DICOUNT_DATA_SUCCESS";
export const UPDATE_DICOUNT_DATA_ERROR = "UPDATE_DICOUNT_DATA_ERROR";
export const UPDATE_NO_OF_MONTH_SUCCESS = "UPDATE_NO_OF_MONTH_SUCCESS";
export const UPDATE_NO_OF_MONTH_ERROR = "UPDATE_NO_OF_MONTH_ERROR";
